server:
  port: 8010

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=TRUE&useSSL=false&serverTimezone=Asia/Shanghai
    hikari:
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        #指定集群名称
        cluster-name: SZ
        #指定命名空间
        #namespace: cf34d89f-d8d3-4533-8478-83be813b0e4b
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
      bindings:
        input:
          destination: stream-test-topic
          #一定要设置 rocket MQ
          #如果用的是其他MQ，这个可以不用设置
          group: binder-group
  application:
    name: user-center

rocketmq:
  name-server: 127.0.0.1:9876
